name: flutter_app
description: Flutter UI for the aider-core Rust logic.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.0.0
  path_provider: ^2.0.15
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0
  dio: ^5.4.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
