[package]
name = "aider-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aider-core = { path = "../core" }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
