name: dart_cli
description: Dart front-end for the cli_tui sidecar.
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  dio: ^5.4.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
