// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> llm({required String prompt}) =>
    RustLib.instance.api.crateApiLlm(prompt: prompt);

Future<String> repoMap() => RustLib.instance.api.crateApiRepoMap();

Future<String> voiceRecord() => RustLib.instance.api.crateApiVoiceRecord();

Future<String> git({required String command}) =>
    RustLib.instance.api.crateApiGit(command: command);

Future<String> scrapeUrl({required String url}) =>
    RustLib.instance.api.crateApiScrapeUrl(url: url);

Future<bool> analyticsEvent({
  required String event,
  required String properties,
}) =>
    RustLib.instance.api
        .crateApiAnalyticsEvent(event: event, properties: properties);
